on: [push]
jobs:
  CV-job: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: CV_holder
      - run: rm -f main.pdf
      - uses: actions/checkout@v2
      - run: sudo docker build --tag fedora .
      - run: sudo docker run --name=fedora fedora
      - run: sudo docker cp fedora:CV/main.pdf ./
      - uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: ./main.pdf
      - uses: EndBug/add-and-commit@v7.5.0
        with:
          add: './main.pdf'
          branch: CV_holder
          message: 'update CV'
